services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 85192577
      POSTGRES_USER: hamedmiri72
      POSTGRES_DB: prismaDB
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:

